### ISSUE TITLE
Add auto refresh rate configuration

### ISSUE THREAD

**Issue by joserenatosilva** [globocom/huskyCI-dashboard#13]
It would be nice to have a dropdown or something similar to let the client decide the refresh rate of the dashboard.

**Comment by douglas-neves** [comment]
Hi everyone,  i open this PR: https://github.com/globocom/huskyCI-dashboard/pull/44

I've added a select box using this Select material ui component, but if necessary is easy change for text input ...
![image](https://user-images.githubusercontent.com/7130956/66490878-3eb4d100-ea88-11e9-82c7-4583df93b9cd.png)

**Comment by rafaveira3** [comment]
Hello, everyone! After discussing internally with the huskyCI team, we have decided that this feature may not provide us so much value at this moment. We are closing it for now as we are redesigning how our dashboard will be displayed to development teams. Thank you all so much for working on this though.
