### ISSUE TITLE
Let users define the dashboard's time range

### ISSUE THREAD

**Issue by joserenatosilva** [globocom/huskyCI-dashboard#14]
It would be nice to let the client decide which time range he wants to see in the huskyCI dashboard.
Currently, we have 5 time ranges that can be queried: `today`, `yesterday`, `last7days` and `last30days` and all-time (no time range set).

**Comment by tclemos** [comment]
Hey @joserenatosilva I'd like to help with this issue.

Where do I find this `ranges`? Tried to execute the dashboard following the instructions on Readme, but only got this:

![Screen Shot 2019-10-03 at 14 29 01](https://user-images.githubusercontent.com/1298871/66149776-307b3680-e5ea-11e9-86ef-431f346016bb.png)

I'm missing something?

**Comment by edgarberlinck** [comment]
I'm not familiar with GO and looking at **huskyCI** repo doesn't helps me to find ou which parameter should I sent to `/analysis` to define the `range`.

Could give us more details?

**Comment by rafaveira3** [comment]
Hello, everyone! After discussing internally with the huskyCI team, we have decided that this feature may not provide us so much value at this moment. We are closing it for now as we are redesigning how our dashboard will be displayed to development teams. Thank you all so much for working on this though.
