### ISSUE TITLE
Dashboard filters

### ISSUE THREAD

**Issue by joserenatosilva** [globocom/huskyCI-dashboard#15]
Add filters to the huskyCI dashboard, i.e. filter by language, vulnerability level and etc.

**Comment by UsefulHunter** [comment]
I can take this one, if no one already solved.

**Comment by rafaveira3** [comment]
Hello, everyone! After discussing internally with the huskyCI team, we have decided that this feature may not provide us so much value at this moment. We are closing it for now as we are redesigning how our dashboard will be displayed to development teams. Thank you all so much for working on this though.
