### ISSUE TITLE
Refactor Dashboard component into smaller modular components

### ISSUE THREAD

**Issue by HectorNM** [globocom/huskyCI-dashboard#20]
Hi, congratulations for this project!

I'm thinking about solving opened issues, so I was reading this project code and I realized most of the application logic and rendering is concentrated inside Dashboard component.

Since there are plans to grow this project with other features listed in opened issues (filters, etc), do you think it could benefit from a refactor, for example, separating `<Dashboard>` into smaller components, like `<Developers>`, `<Analyses>` and `<Repositories>`? Of course there is some cost associated with this refactor, since some logic would have to be rewritten and then some data would have to be grouped together in the parent component (in this case, `<Dashboard>`... So that's why I'm questioning: do you think it is worth to refactor? :)

Thank you for your time!

**Comment by rafaveira3** [comment]
Hey, @HectorNM! Thanks a lot for reaching out! We are very happy to receive these kinds of feedback from our code. 🙃

We have started building this FE using [create-react-app](https://github.com/facebook/create-react-app) but didn't know how we could create these components at that time. 

And, YES! I agree with you! 👍🏻 Actually, we have 6 types of data at this moment: `Developers`, `Analyses`, `Repositories`, `Containers`, `Language`, `Results`. 

We can create an issue (or two? whatever you prefer) for this refactoring, if you would like to work on them, of course! I will also be very happy to add the `hacktoberfest` on them so you can participate in our [Hacktoberfest](https://opensource.globo.com/hacktoberfest/). What do you think? 😄
