### ISSUE TITLE
Add a login page 

### ISSUE THREAD

**Issue by rafaveira3** [globocom/huskyCI-dashboard#30]
Since we intend to code an [OpenID Connect feature](https://github.com/globocom/huskyCI/issues/367) on huskyCI, it would be great to have a login page with the options similar to: 

![image](https://user-images.githubusercontent.com/8943477/66124165-13c70a80-e5ba-11e9-9a46-db7cc1cde9c3.png)

**Comment by edumoreira1506** [comment]
I will work in this issue!

**Comment by rafaveira3** [comment]
Cool, @edumoreira1506! Thanks a lot for reaching out and tackling this one! Looking forward to reviewing your PR or receiving any other feedback from you. 🙃
