### ISSUE TITLE
Add a top Bar with a Logout button 

### ISSUE THREAD

**Issue by rafaveira3** [globocom/huskyCI-dashboard#31]
As we intend to have authentication on huskyCI, it would be cool to have a top bar with the logout option. It would be great if we also have the developer profile picture as we may get it from Gitlab/Github OpenID Connect auth. 

Something similar to: 

![image](https://user-images.githubusercontent.com/8943477/66124362-89cb7180-e5ba-11e9-9293-8b48c8fe60e3.png)

**Comment by rubynho** [comment]
I'd like to work on this issue.

**Comment by rafaveira3** [comment]
Absolutely, @rubynho! Thanks a lot for reaching out and tackling this one! Looking forward to reviewing your PR or any other feedbacks you could send to us. 🙃

**Comment by tclemos** [comment]
@rubynho not sure if you are still working on this, but I also got engaged to work on that. 
My PR #34 is open and maybe it can help you out with your version.
